/**
 * HealthReports - Generate health summaries from chat history
 */

"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { X, FileText, Download, Calendar, MessageSquare, TrendingUp } from "lucide-react"
import { Button } from "@/components/ui/button"
import type { Chat } from "@/lib/types"

interface HealthReportsProps {
  onClose: () => void
  chats: Chat[]
}

export default function HealthReports({ onClose, chats }: HealthReportsProps) {
  const [isGenerating, setIsGenerating] = useState(false)
  const [report, setReport] = useState<string | null>(null)

  const totalMessages = chats.reduce((acc, chat) => acc + chat.messages.length, 0)
  const totalChats = chats.length

  const generateReport = async () => {
    setIsGenerating(true)
    await new Promise((resolve) => setTimeout(resolve, 2000))

    setReport(`# MEDIC Health Summary Report
Generated: ${new Date().toLocaleDateString()}

## Conversation Overview
- Total conversations: ${totalChats}
- Total messages: ${totalMessages}
- Period: Last 30 days

## Topics Discussed
Based on your conversations, here are the main health topics you've inquired about:

1. **General Health Questions** - Routine health inquiries
2. **Symptom Information** - Understanding various symptoms
3. **Medication Guidance** - Drug information and interactions

## Key Recommendations
- Continue maintaining regular check-ups with your healthcare provider
- Keep track of any recurring symptoms
- Follow prescribed medication schedules

## Disclaimer
This report is generated from your MEDIC conversations and is for informational purposes only. It does not constitute medical advice or diagnosis.

---
*Report generated by MEDIC AI Medical Assistant*`)

    setIsGenerating(false)
  }

  const downloadReport = () => {
    if (!report) return
    const blob = new Blob([report], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `medic-health-report-${new Date().toISOString().split("T")[0]}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[var(--z-modal)] flex items-center justify-center bg-background/80 backdrop-blur-sm p-4"
      onClick={(e) => e.target === e.currentTarget && onClose()}
      role="dialog"
      aria-modal="true"
      aria-labelledby="health-reports-title"
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 20 }}
        transition={{ type: "spring", stiffness: 400, damping: 30 }}
        className="flex max-h-[85vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-border bg-popover shadow-cinematic"
      >
        {/* Header - Fixed */}
        <div className="flex shrink-0 items-center justify-between border-b border-border p-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-violet-500 to-purple-500">
              <FileText className="h-5 w-5 text-white" />
            </div>
            <div>
              <h2 id="health-reports-title" className="text-lg font-semibold text-foreground">
                Health Reports
              </h2>
              <p className="text-xs text-muted-foreground">Generate summaries from your conversations</p>
            </div>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} aria-label="Close health reports">
            <X className="h-5 w-5" />
          </Button>
        </div>

        <div className="flex-1 overflow-y-auto custom-scrollbar">
          <div className="p-4 space-y-4">
            {/* Stats */}
            <div className="grid grid-cols-3 gap-3">
              <div className="rounded-xl border border-border bg-muted/30 p-4 text-center">
                <MessageSquare className="mx-auto mb-2 h-6 w-6 text-primary" />
                <p className="text-2xl font-bold text-foreground">{totalChats}</p>
                <p className="text-xs text-muted-foreground">Conversations</p>
              </div>
              <div className="rounded-xl border border-border bg-muted/30 p-4 text-center">
                <TrendingUp className="mx-auto mb-2 h-6 w-6 text-primary" />
                <p className="text-2xl font-bold text-foreground">{totalMessages}</p>
                <p className="text-xs text-muted-foreground">Messages</p>
              </div>
              <div className="rounded-xl border border-border bg-muted/30 p-4 text-center">
                <Calendar className="mx-auto mb-2 h-6 w-6 text-primary" />
                <p className="text-2xl font-bold text-foreground">30</p>
                <p className="text-xs text-muted-foreground">Days</p>
              </div>
            </div>

            {!report ? (
              <div className="text-center py-8">
                <FileText className="mx-auto mb-4 h-12 w-12 text-muted-foreground" />
                <h3 className="mb-2 text-lg font-medium text-foreground">Generate Health Summary</h3>
                <p className="mb-4 text-sm text-muted-foreground">
                  Create a summary report based on your conversation history with MEDIC.
                </p>
                <Button
                  onClick={generateReport}
                  disabled={isGenerating}
                  className="gap-2 bg-gradient-to-r from-primary to-secondary"
                >
                  {isGenerating ? (
                    <>
                      <motion.div
                        animate={{ rotate: 360 }}
                        transition={{ duration: 1, repeat: Number.POSITIVE_INFINITY, ease: "linear" }}
                        className="h-4 w-4 rounded-full border-2 border-current border-t-transparent"
                      />
                      Generating Report...
                    </>
                  ) : (
                    <>
                      <FileText className="h-4 w-4" />
                      Generate Report
                    </>
                  )}
                </Button>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="rounded-xl border border-border bg-muted/30 p-4">
                  <pre className="whitespace-pre-wrap text-sm text-foreground/90 font-sans">{report}</pre>
                </div>
                <div className="flex gap-2">
                  <Button onClick={downloadReport} className="flex-1 gap-2">
                    <Download className="h-4 w-4" />
                    Download Report
                  </Button>
                  <Button variant="outline" onClick={() => setReport(null)}>
                    Generate New
                  </Button>
                </div>
              </div>
            )}
          </div>
        </div>
      </motion.div>
    </motion.div>
  )
}
